name: Extract 7z Archive

on: 
  push:
    branches:
      - main  # استخدم اسم الفرع الذي تريده، مثل "main" أو "master"

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install p7zip
        run: sudo apt-get install -y p7zip-full

      - name: Extract 7z archive
        run: 7z x yourfile.7z -o./extracted_files  # استبدل "yourfile.7z" بالاسم الفعلي لملفك

      - name: Commit extracted files
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"
          git add extracted_files
          git commit -m "Extracted files from 7z archive"
          git push
