name: Extract 7z Archive

on: 
  push:
    branches:
      - main  # استخدم اسم الفرع الصحيح، مثل "main" أو "master"

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install p7zip
        run: sudo apt-get install -y p7zip-full

      - name: List repository contents (Debugging)
        run: ls -la

      - name: Extract 7z archive
        run: 7z x "sustainability_app V1.1.7z" -o./extracted_files || 7z x sustainability_app_V1.1.7z -o./extracted_files

      - name: List extracted files (Debugging)
        run: ls -la extracted_files

      - name: Commit extracted files
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"
          git add extracted_files
          git commit -m "Extracted files from 7z archive"
          git push
